version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values[span_0](end_span)
    directory: "/" # Location of package manifests[span_1](end_span)
    schedule:
      interval: "daily"
