version: 2
updates:
  - [span_0](start_span)package-ecosystem: "pip" # See documentation for possible values[span_0](end_span)
    [span_1](start_span)directory: "/" # Location of package manifests[span_1](end_span)
    schedule:
      interval: "daily"
    # 'ignore' is now an array (list) with one item
    ignore:
      - update-types: [ "version-update:semver-major" ]
