# fly.toml app configuration file generated for spice-tracker-bot-wlpasq on 2025-08-30T03:49:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spice-tracker-bot-wlpasq'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
